export const ROUTES = {
  HOME: "/",
  WORK_IN_PROGRESS: "/work-in-progress",
  EMAIL_SENT: "/email-sent",
  PIN_VERIFICATION: (userPin) => `/pin-verification/${userPin}`,
  PERSONAL: "/personal",
  PERSONAL_EVENT: (slug) => `/personal/${slug}`,
  EVENT: (eventSlug) => `/event/${eventSlug}`,
  EVENT_WITH_HASH: (eventSlug, userHash) => `/event/${eventSlug}/${userHash}`,
  PROCESSING_SELFIE: "/processing-selfie",
  CONTENT_UNAVAILABLE: "/content-unavailable",
  PRE_ORDER: "/pre-order",
  PRE_ORDER_PURCHASED: "/pre-order-purchased",
  IMAGE_SHOP: "/image-shop",
  CHOOSE_PAYMENT: "/choose-payment",
  PAY_AT_COUNTER: "/pay-at-counter",
  CHECKOUT: "/checkout",
  CHECKOUT_OUTCOME: "/checkout-outcome",
  MAIL_CONFIRMATION: "/mail-confirmation",
  THANK_YOU: "/thank-you",
  PURCHASED: "/purchased",
  PROCESSING_PHOTOS: "/processing-photos",
  CONTENT_ERROR: "/content-error",
  ADMIN: "/admin",
  ADMIN_EVENTS: "/admin/events",
  ADMIN_CREATE_EVENT: "/admin/create-event",
  ADMIN_EVENT: (eventId) => `/admin/event/${eventId}`,
  ADMIN_READERS: "/admin/readers",
  ADMIN_READER: (readerId) => `/admin/readers/${readerId}`,
  ADMIN_LOCATIONS: "/admin/locations",
};
